{
 "title": "Cockpit",
 "time": { "to": "now", "from": "now-2d" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo, current-tripleo-rdo-testing"
   },
   { "name": "releases", "query": "master, queens, pike, ocata" },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Upstream Zuul queue",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 10, "w": 5, "x": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "tripleo", "key": "queue", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RDO Zuul queue",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 10, "w": 5, "x": 5 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" }
     ],
     "measurement": "zuul-queue-status",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gate jobs",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 10, "w": 5, "x": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "False", "key": "passed", "condition": "AND" }
     ],
     "measurement": "build",
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Check jobs (noop)",
   "type": "singlestat",
   "gridPos": { "y": 1, "h": 10, "w": 4, "x": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "560445", "key": "change" },
      { "operator": "=", "value": "567224", "key": "change", "condition": "OR" },
      { "operator": "=", "value": "564291", "key": "change", "condition": "OR" },
      { "operator": "=", "value": "564285", "key": "change", "condition": "OR" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" },
      { "operator": "=", "value": "False", "key": "passed", "condition": "AND" }
     ],
     "measurement": "build",
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ],
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE ((\"change\" = '560445' OR \"change\" = '567224' OR \"change\" = '564291' OR \"change\" = '564285' ) AND \"voting\" = 'True' AND \"passed\" = 'False') AND $timeFilter",
     "groupBy": [
      { "type": "time", "params": [ "6h" ] },
      { "type": "fill", "params": [ "none" ] }
     ]
    }
   ]
  },
  {
   "title": "CI stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "y": 1, "h": 10, "w": 5, "x": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "True", "key": "passed" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "0" ] }
     ],
     "alias": "PASS",
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "False", "key": "passed" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "0" ] }
     ],
     "alias": "FAIL",
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failing gate jobs",
   "type": "table",
   "gridPos": { "y": 11, "h": 7, "w": 11, "x": 0 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "False", "key": "passed" },
      { "operator": "=", "value": "gate", "key": "pipeline", "condition": "AND" }
     ],
     "measurement": "build",
     "select": [
      [
       { "type": "field", "params": [ "branch" ] }
      ],
      [
       { "type": "field", "params": [ "change" ] }
      ],
      [
       { "type": "field", "params": [ "log_link" ] }
      ],
      [
       { "type": "field", "params": [ "duration" ] }
      ],
      [
       { "type": "field", "params": [ "cloud" ] }
      ],
      [
       { "type": "field", "params": [ "region" ] }
      ]
     ],
     "query": "SELECT \"duration\", \"result\", \"log_url\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' ) AND $timeFilter GROUP BY \"job_name\", \"branch\", \"pipeline\", \"change\""
    }
   ]
  },
  {
   "title": "Failing check jobs (noop)",
   "type": "table",
   "gridPos": { "y": 11, "h": 7, "w": 13, "x": 11 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "False", "key": "passed" },
      { "operator": "=", "value": "560445", "key": "change", "condition": "AND" },
      { "operator": "=", "value": "567224", "key": "change", "condition": "OR" },
      { "operator": "=", "value": "564291", "key": "change", "condition": "OR" },
      { "operator": "=", "value": "564285", "key": "change", "condition": "OR" }
     ],
     "measurement": "build",
     "select": [
      [
       { "type": "field", "params": [ "log_link" ] }
      ],
      [
       { "type": "field", "params": [ "duration" ] }
      ],
      [
       { "type": "field", "params": [ "result" ] }
      ]
     ],
     "query": "SELECT \"branch\", \"pipeline\", \"change\", \"patchset\", \"job_name\", \"log_link\",  \"duration\", \"cloud\", \"region\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND (\"change\" = '560445' OR \"change\" = '567224' OR \"change\" = '564291' OR \"change\" = '564285') AND \"voting\" = 'True') AND $timeFilter ",
     "groupBy": [
      { "type": "tag", "params": [ "job_name" ] },
      { "type": "tag", "params": [ "branch" ] },
      { "type": "tag", "params": [ "pipeline" ] },
      { "type": "tag", "params": [ "change" ] }
     ]
    }
   ]
  },
  {
   "title": "$launchpad_tags bugs",
   "type": "table",
   "gridPos": { "y": 18, "h": 6, "w": 11, "x": 0 },
   "targets": [
    {
     "tags": [
      { "operator": "=~", "value": "/^$launchpad_tags$/", "key": "tag" }
     ],
     "measurement": "launchpad-bug",
     "select": [
      [
       { "type": "field", "params": [ "title" ] }
      ],
      [
       { "type": "field", "params": [ "status" ] }
      ],
      [
       { "type": "field", "params": [ "id" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotion blockers",
   "type": "table",
   "gridPos": { "y": 18, "h": 6, "w": 13, "x": 11 },
   "targets": [
    {
     "slimit": "1",
     "tags": [
      { "operator": "=", "value": "promotion-blocker", "key": "tag" }
     ],
     "measurement": "launchpad-bug",
     "select": [
      [
       { "type": "field", "params": [ "title" ] }
      ],
      [
       { "type": "field", "params": [ "status" ] }
      ],
      [
       { "type": "field", "params": [ "id" ] }
      ]
     ]
    }
   ]
  },
  { "title": "Promoter alerts", "type": "alertlist", "gridPos": { "y": 24, "h": 6, "w": 5, "x": 0 } },
  { "title": "Tripleo CI promotion alerts", "type": "alertlist", "gridPos": { "y": 24, "h": 6, "w": 5, "x": 5 } },
  { "title": "Phase 1 promotions alerts", "type": "alertlist", "gridPos": { "y": 24, "h": 6, "w": 5, "x": 10 } },
  { "title": "Phase 2 promotions alerts", "type": "alertlist", "gridPos": { "y": 24, "h": 6, "w": 5, "x": 15 } },
  { "title": "Jobs enqueued time alerts", "type": "alertlist", "gridPos": { "y": 30, "h": 6, "w": 5, "x": 0 } },
  { "title": "Noop changes alerts", "type": "alertlist", "gridPos": { "y": 30, "h": 6, "w": 5, "x": 5 } },
  { "title": "Gate jobs alerts", "type": "alertlist", "gridPos": { "y": 30, "h": 3, "w": 5, "x": 10 } },
  { "title": "Infra issues", "type": "alertlist", "gridPos": { "y": 30, "h": 6, "w": 5, "x": 15 } },
  { "title": "RDO Nodepool alerts", "type": "alertlist", "gridPos": { "y": 33, "h": 3, "w": 5, "x": 10 } },
  { "title": "Zuul jobs", "type": "row", "gridPos": { "y": 36, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "CI stats weekly",
   "type": "graph",
   "gridPos": { "y": 37, "h": 7, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "True", "key": "passed" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "24h" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "PASS",
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "False", "key": "passed" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "24h" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "FAIL",
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream zuul max enqueued time",
   "type": "graph",
   "gridPos": { "y": 44, "h": 6, "w": 4, "x": 0 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "tripleo", "key": "queue", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RDO zuul max enqueued time",
   "type": "graph",
   "gridPos": { "y": 44, "h": 6, "w": 4, "x": 4 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" }
     ],
     "measurement": "zuul-queue-status",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "openstack-check",
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream gate jobs",
   "type": "graph",
   "gridPos": { "y": 44, "h": 6, "w": 16, "x": 8 },
   "yaxes": [
    { "format": "short", "label": "Number of builds" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "True", "key": "passed", "condition": "AND" },
      { "operator": "=", "value": "upstream", "key": "type", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "30m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "PASSED",
     "select": [
      [
       { "type": "field", "params": [ "result" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "False", "key": "passed", "condition": "AND" },
      { "operator": "=", "value": "upstream", "key": "type", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "30m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "FAILED",
     "select": [
      [
       { "type": "field", "params": [ "result" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Check voting  jobs",
   "type": "graph",
   "gridPos": { "y": 50, "h": 6, "w": 12, "x": 0 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "check", "key": "pipeline" },
      { "operator": "=", "value": "True", "key": "passed", "condition": "AND" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "30m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "PASSED",
     "select": [
      [
       { "type": "field", "params": [ "result" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "check", "key": "pipeline" },
      { "operator": "=", "value": "False", "key": "passed", "condition": "AND" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "30m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "FAILED",
     "select": [
      [
       { "type": "field", "params": [ "result" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Check  jobs",
   "type": "graph",
   "gridPos": { "y": 50, "h": 6, "w": 12, "x": 12 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "check", "key": "pipeline" },
      { "operator": "=", "value": "True", "key": "passed", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "30m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "PASSED",
     "select": [
      [
       { "type": "field", "params": [ "result" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "check", "key": "pipeline" },
      { "operator": "=", "value": "False", "key": "passed", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "time", "params": [ "30m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "alias": "FAILED",
     "select": [
      [
       { "type": "field", "params": [ "result" ] },
       {
        "type": "count",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Master noop change results",
   "type": "graph",
   "gridPos": { "y": 56, "h": 4, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "Result code" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "560445", "key": "change" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "tag", "params": [ "job_name" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ocata noop change results",
   "type": "graph",
   "gridPos": { "y": 56, "h": 4, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "Result code" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "564291", "key": "change" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "tag", "params": [ "job_name" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queens noop change results",
   "type": "graph",
   "gridPos": { "y": 60, "h": 4, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "Result code" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "567224", "key": "change" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "tag", "params": [ "job_name" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pîke noop change results",
   "type": "graph",
   "gridPos": { "y": 60, "h": 4, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "Result code" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "564285", "key": "change" },
      { "operator": "=", "value": "True", "key": "voting", "condition": "AND" }
     ],
     "measurement": "build",
     "groupBy": [
      { "type": "tag", "params": [ "job_name" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "result_num" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last jobs",
   "type": "table",
   "gridPos": { "y": 64, "h": 10, "w": 24, "x": 0 },
   "targets": [
    {
     "measurement": "build",
     "select": [
      [
       { "type": "field", "params": [ "branch" ] }
      ],
      [
       { "type": "field", "params": [ "change" ] }
      ],
      [
       { "type": "field", "params": [ "log_link" ] }
      ],
      [
       { "type": "field", "params": [ "duration" ] }
      ],
      [
       { "type": "field", "params": [ "result_num" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions",
   "type": "row",
   "gridPos": { "y": 74, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Promotions for master tripleo ci",
     "type": "graph",
     "gridPos": { "y": 3, "h": 4, "w": 5, "x": 0 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "master", "key": "release" },
        { "operator": "=", "value": "current-tripleo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for master phase 1",
     "type": "graph",
     "gridPos": { "y": 3, "h": 4, "w": 5, "x": 5 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "master", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for master phase 2",
     "type": "graph",
     "gridPos": { "y": 3, "h": 4, "w": 4, "x": 10 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "master", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo-internal", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for queens tripleo ci",
     "type": "graph",
     "gridPos": { "y": 7, "h": 4, "w": 5, "x": 0 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "queens", "key": "release" },
        { "operator": "=", "value": "current-tripleo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for queens phase 1",
     "type": "graph",
     "gridPos": { "y": 7, "h": 4, "w": 5, "x": 5 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "queens", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for queens phase 2",
     "type": "graph",
     "gridPos": { "y": 7, "h": 4, "w": 4, "x": 10 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "queens", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo-internal", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for pike tripleo ci",
     "type": "graph",
     "gridPos": { "y": 11, "h": 4, "w": 5, "x": 0 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "pike", "key": "release" },
        { "operator": "=", "value": "current-tripleo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for pike phase 1",
     "type": "graph",
     "gridPos": { "y": 11, "h": 4, "w": 5, "x": 5 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "pike", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for pike phase 2",
     "type": "graph",
     "gridPos": { "y": 11, "h": 4, "w": 4, "x": 10 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "pike", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo-internal", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for ocata tripleo ci",
     "type": "graph",
     "gridPos": { "y": 15, "h": 4, "w": 5, "x": 0 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "ocata", "key": "release" },
        { "operator": "=", "value": "current-tripleo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for ocata phase 1",
     "type": "graph",
     "gridPos": { "y": 15, "h": 4, "w": 5, "x": 5 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "ocata", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Promotions for ocata phase 2",
     "type": "graph",
     "gridPos": { "y": 15, "h": 4, "w": 4, "x": 10 },
     "yaxes": [
      { "format": "short", "label": "Number of promotions" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "ocata", "key": "release" },
        { "operator": "=", "value": "current-tripleo-rdo-internal", "key": "name", "condition": "AND" }
       ],
       "measurement": "dlrn-promotion",
       "groupBy": [
        { "type": "time", "params": [ "24h" ] },
        { "type": "tag", "params": [ "name" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] },
         {
          "type": "count",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DLRN promoter master",
     "type": "graph",
     "gridPos": { "y": 19, "h": 4, "w": 7, "x": 0 },
     "yaxes": [
      { "format": "percent", "label": "CPU time" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "promoter-server.rdocloud", "key": "host" },
        {
         "operator": "=",
         "value": "^python.*dlrnapi_promoter.py .*master.*",
         "key": "pattern",
         "condition": "AND"
        }
       ],
       "measurement": "procstat",
       "groupBy": [
        { "type": "time", "params": [ "1m" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "cpu_time_user" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DLRN promoter queens",
     "type": "graph",
     "gridPos": { "y": 19, "h": 4, "w": 7, "x": 7 },
     "yaxes": [
      { "format": "percent", "label": "CPU time" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "promoter-server.rdocloud", "key": "host" },
        {
         "operator": "=",
         "value": "^python.*dlrnapi_promoter.py .*queens.*",
         "key": "pattern",
         "condition": "AND"
        }
       ],
       "measurement": "procstat",
       "groupBy": [
        { "type": "time", "params": [ "1m" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "cpu_time_user" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DLRN promoter pike",
     "type": "graph",
     "gridPos": { "y": 23, "h": 4, "w": 7, "x": 0 },
     "yaxes": [
      { "format": "percent", "label": "CPU time" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "promoter-server.rdocloud", "key": "host" },
        {
         "operator": "=",
         "value": "^python.*dlrnapi_promoter.py .*pike.*",
         "key": "pattern",
         "condition": "AND"
        }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "type": "field", "params": [ "cpu_time_user" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ],
       "query": "SELECT \"cpu_time\", \"read_bytes\", \"write_bytes\", \"pid\" FROM \"procstat\" WHERE (\"host\" = 'promoter-server.rdocloud' AND \"pattern\" = '^python.*dlrnapi_promoter.py .*queens.*') AND $timeFilter",
       "groupBy": [
        { "type": "time", "params": [ "1m" ] },
        { "type": "fill", "params": [ "0" ] }
       ]
      }
     ]
    },
    {
     "title": "DLRN promoter ocata",
     "type": "graph",
     "gridPos": { "y": 23, "h": 4, "w": 7, "x": 7 },
     "yaxes": [
      { "format": "percent", "label": "CPU time" }
     ],
     "targets": [
      {
       "tags": [
        { "operator": "=", "value": "promoter-server.rdocloud", "key": "host" },
        {
         "operator": "=",
         "value": "^python.*dlrnapi_promoter.py .*ocata.*",
         "key": "pattern",
         "condition": "AND"
        }
       ],
       "measurement": "procstat",
       "groupBy": [
        { "type": "time", "params": [ "1m" ] },
        { "type": "fill", "params": [ "0" ] }
       ],
       "select": [
        [
         { "type": "field", "params": [ "cpu_time_user" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Skipped $releases promotions",
     "type": "table",
     "gridPos": { "y": 27, "h": 7, "w": 24, "x": 0 },
     "repeat": "releases",
     "targets": [
      {
       "tags": [
        { "operator": "=~", "value": "/^$releases$/", "key": "release" }
       ],
       "measurement": "skipped-promotions",
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] }
        ],
        [
         { "type": "field", "params": [ "from_name" ] }
        ],
        [
         { "type": "field", "params": [ "to_name" ] }
        ],
        [
         { "type": "field", "params": [ "failing_jobs" ] }
        ]
       ]
      }
     ]
    },
    {
     "title": "Skipped $releases promotions",
     "type": "table",
     "gridPos": { "y": 34, "h": 7, "w": 24, "x": 0 },
     "targets": [
      {
       "tags": [
        { "operator": "=~", "value": "/^$releases$/", "key": "release" }
       ],
       "measurement": "skipped-promotions",
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] }
        ],
        [
         { "type": "field", "params": [ "from_name" ] }
        ],
        [
         { "type": "field", "params": [ "to_name" ] }
        ],
        [
         { "type": "field", "params": [ "failing_jobs" ] }
        ]
       ]
      }
     ]
    },
    {
     "title": "Skipped $releases promotions",
     "type": "table",
     "gridPos": { "y": 41, "h": 7, "w": 24, "x": 0 },
     "targets": [
      {
       "tags": [
        { "operator": "=~", "value": "/^$releases$/", "key": "release" }
       ],
       "measurement": "skipped-promotions",
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] }
        ],
        [
         { "type": "field", "params": [ "from_name" ] }
        ],
        [
         { "type": "field", "params": [ "to_name" ] }
        ],
        [
         { "type": "field", "params": [ "failing_jobs" ] }
        ]
       ]
      }
     ]
    },
    {
     "title": "Skipped $releases promotions",
     "type": "table",
     "gridPos": { "y": 48, "h": 7, "w": 24, "x": 0 },
     "targets": [
      {
       "tags": [
        { "operator": "=~", "value": "/^$releases$/", "key": "release" }
       ],
       "measurement": "skipped-promotions",
       "select": [
        [
         { "type": "field", "params": [ "repo_hash" ] }
        ],
        [
         { "type": "field", "params": [ "from_name" ] }
        ],
        [
         { "type": "field", "params": [ "to_name" ] }
        ],
        [
         { "type": "field", "params": [ "failing_jobs" ] }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "y": 75, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Openstack infra issues",
     "type": "table",
     "gridPos": { "y": 76, "h": 7, "w": 24, "x": 0 },
     "targets": [
      {
       "measurement": "openstack-infra-issues",
       "select": [
        [
         { "type": "field", "params": [ "issue" ] }
        ]
       ],
       "query": "SELECT \"issue\" FROM \"openstack-infra-issues\""
      }
     ]
    },
    {
     "title": "Github",
     "type": "table",
     "gridPos": { "y": 83, "h": 9, "w": 12, "x": 0 },
     "targets": [
      {
       "measurement": "github-status",
       "select": [
        [
         { "type": "field", "params": [ "message" ] }
        ],
        [
         { "type": "field", "params": [ "status_enum" ] }
        ]
       ]
      }
     ]
    },
    {
     "title": "Github",
     "type": "graph",
     "gridPos": { "y": 83, "h": 9, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short", "label": "status" }
     ],
     "targets": [
      {
       "measurement": "github-status",
       "select": [
        [
         { "type": "field", "params": [ "status_enum" ] }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "RDO cloud performance", "type": "row", "gridPos": { "y": 76, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Nodes status",
   "type": "graph",
   "gridPos": { "y": 77, "h": 6, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "none" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "ACTIVE" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "ACTIVE" ] }
      ],
      [
       { "type": "field", "params": [ "BUILD" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "BUILD" ] }
      ],
      [
       { "type": "field", "params": [ "DELETED" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "DELETED" ] }
      ],
      [
       { "type": "field", "params": [ "ERROR" ] },
       {
        "type": "mean",
        "params": []
       },
       { "type": "alias", "params": [ "ERROR" ] }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instances types",
   "type": "graph",
   "gridPos": { "y": 77, "h": 6, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "BMC node",
     "select": [
      [
       { "type": "field", "params": [ "bmc" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "Multinode",
     "select": [
      [
       { "type": "field", "params": [ "multinode" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "Undercloud",
     "select": [
      [
       { "type": "field", "params": [ "undercloud" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "OVB BM node",
     "select": [
      [
       { "type": "field", "params": [ "ovb-node" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "Other",
     "select": [
      [
       { "type": "field", "params": [ "other" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "graph",
   "gridPos": { "y": 83, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "CREATE_COMPLETE",
     "select": [
      [
       { "type": "field", "params": [ "create_complete" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "CREATE_FAILED",
     "select": [
      [
       { "type": "field", "params": [ "create_failed" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "CREATE_IN_PROGRESS",
     "select": [
      [
       { "type": "field", "params": [ "create_in_progress" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "DELETE_COMPLETE",
     "select": [
      [
       { "type": "field", "params": [ "delete_complete" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "DELETE_FAILED",
     "select": [
      [
       { "type": "field", "params": [ "delete_failed" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "DELETE_IN_PROGRESS",
     "select": [
      [
       { "type": "field", "params": [ "delete_in_progress" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Problematic stacks",
   "type": "graph",
   "gridPos": { "y": 83, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "Old stacks",
     "select": [
      [
       { "type": "field", "params": [ "old_stacks" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "rdocloud-servers",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "Failed to delete",
     "select": [
      [
       { "type": "field", "params": [ "delete_failed" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "graph",
   "gridPos": { "y": 90, "h": 6, "w": 7, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-perf",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "CPU cores",
     "select": [
      [
       { "type": "field", "params": [ "cores" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "y": 90, "h": 6, "w": 9, "x": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-perf",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "RAM",
     "select": [
      [
       { "type": "field", "params": [ "ram" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "y": 90, "h": 6, "w": 8, "x": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rdocloud-perf",
     "groupBy": [
      { "type": "time", "params": [ "15m" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "alias": "Servers",
     "select": [
      [
       { "type": "field", "params": [ "instances" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  }
 ]
}