{
 "title": "Ruck Rover Cockpit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Zuul", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream job status",
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
   "content": "To look for issue check [sova gate jobs](http://cistatus.tripleo.org/gate/) and [upstream zuul](http://zuul.opentsack.org)"
  },
  {
   "title": "Upstream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "m", "label": "max enqueued time" }
   ],
   "targets": [
    {
     "alias": "tripleo gate",
     "measurement": "zuul-queue-status",
     "query": "SELECT \"enqueued_time\" FROM \"zuul-queue-status\" WHERE (\"pipeline\" = 'gate' AND \"queue\" = 'tripleo') AND $timeFilter",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "min result code" }
   ],
   "targets": [
    {
     "alias": "Tripleo gate",
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "Upstream tripleo gate failures",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 8, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "zuul-queue-status",
     "query": "SELECT \"refspec\", \"job\", \"result\", \"enqueued_time\" FROM \"zuul-queue-status\" WHERE \"pipeline\" = 'gate' AND \"queue\" = 'tripleo' AND $timeFilter AND result_code = -1",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "RDO job status",
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 8 },
   "content": "To look for issue check [sova promotion jobs](http://cistatus.tripleo.org/promotion/) and [RDO zuul](http://review.rdoproject.org/zuul)"
  },
  {
   "title": "RDO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "m", "label": "max enqueued time" }
   ],
   "targets": [
    {
     "alias": "openstack-check",
     "measurement": "zuul-queue-status",
     "query": "SELECT \"enqueued_time\" FROM \"zuul-queue-status\" WHERE (\"pipeline\" = 'gate' AND \"queue\" = 'tripleo') AND $timeFilter",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "openstack-check" },
      {
       "condition": "AND",
       "key": "url",
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json"
      }
     ]
    }
   ]
  },
  {
   "title": "RDO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "min result code" }
   ],
   "targets": [
    {
     "alias": "openstack-check (560445)",
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "openstack-check" },
      {
       "condition": "AND",
       "key": "url",
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json"
      },
      { "condition": "AND", "key": "review", "operator": "=", "value": "560445" }
     ]
    },
    {
     "alias": "openstack-check (567224)",
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "openstack-check" },
      {
       "condition": "AND",
       "key": "url",
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json"
      },
      { "condition": "AND", "key": "review", "operator": "=", "value": "567224" }
     ]
    },
    {
     "alias": "openstack-check (564285)",
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "openstack-check" },
      {
       "condition": "AND",
       "key": "url",
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json"
      },
      { "condition": "AND", "key": "review", "operator": "=", "value": "564285" }
     ]
    },
    {
     "alias": "openstack-check (564291)",
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "openstack-check" },
      {
       "condition": "AND",
       "key": "url",
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json"
      },
      { "condition": "AND", "key": "review", "operator": "=", "value": "564291" }
     ]
    }
   ]
  },
  {
   "title": "RDO openstack-check noop failures",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "zuul-queue-status",
     "query": "SELECT \"job\", \"review\", \"patch_set\", \"result\" FROM \"zuul-queue-status\" WHERE result_code=-1 AND \"pipeline\" = 'openstack-check' AND \"url\" = 'https://review.rdoproject.org/zuul/status.json' AND $timeFilter AND (\"review\"='560445' OR \"review\"='567224' OR \"review\"='564285 ' OR \"review\"='564291' )",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "openstack-check" },
      {
       "condition": "AND",
       "key": "url",
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json"
      }
     ]
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Urgent bugs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "urgent-bugs",
     "query": "SELECT \"title\", \"status\", \"link\" FROM \"urgent-bugs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "title" ], "type": "field" }
      ],
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "link" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Openstack infra issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 16 },
   "targets": [
    {
     "measurement": "openstack-infra-issues",
     "query": "SELECT \"issue\" FROM \"openstack-infra-issues\"",
     "select": [
      [
       { "params": [ "issue" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}