{
 "title": "Ruck Rover",
 "time": { "to": "now", "from": "now-6d" },
 "panels": [
  { "title": "Zuul", "type": "row", "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Upstream job status",
   "type": "text",
   "gridPos": { "y": 1, "h": 2, "w": 22, "x": 0 },
   "content": "To look for issue check [sova gate jobs](http://cistatus.tripleo.org/gate/) and [upstream zuul](http://zuul.opentsack.org)"
  },
  {
   "title": "Upstream",
   "type": "graph",
   "gridPos": { "y": 3, "h": 5, "w": 4, "x": 0 },
   "yaxes": [
    { "format": "m", "label": "max enqueued time" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "tripleo", "key": "queue", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "alias": "tripleo gate",
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ],
     "query": "SELECT \"enqueued_time\" FROM \"zuul-queue-status\" WHERE (\"pipeline\" = 'gate' AND \"queue\" = 'tripleo') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "graph",
   "gridPos": { "y": 3, "h": 5, "w": 4, "x": 4 },
   "yaxes": [
    { "format": "short", "label": "min result code" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "tripleo", "key": "queue", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "alias": "Tripleo gate",
     "select": [
      [
       { "type": "field", "params": [ "result_code" ] },
       {
        "type": "min",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream tripleo gate failures",
   "type": "table",
   "gridPos": { "y": 3, "h": 5, "w": 14, "x": 8 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "gate", "key": "pipeline" },
      { "operator": "=", "value": "tripleo", "key": "queue", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] }
      ]
     ],
     "query": "SELECT \"refspec\", \"job\", \"result\", \"enqueued_time\" FROM \"zuul-queue-status\" WHERE \"pipeline\" = 'gate' AND \"queue\" = 'tripleo' AND $timeFilter AND result_code = -1",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ]
    }
   ]
  },
  {
   "title": "RDO job status",
   "type": "text",
   "gridPos": { "y": 8, "h": 2, "w": 22, "x": 0 },
   "content": "To look for issue check [sova promotion jobs](http://cistatus.tripleo.org/promotion/) and [RDO zuul](http://review.rdoproject.org/zuul)"
  },
  {
   "title": "RDO",
   "type": "graph",
   "gridPos": { "y": 10, "h": 5, "w": 4, "x": 0 },
   "yaxes": [
    { "format": "m", "label": "max enqueued time" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" },
      {
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json",
       "key": "url",
       "condition": "AND"
      }
     ],
     "measurement": "zuul-queue-status",
     "alias": "openstack-check",
     "select": [
      [
       { "type": "field", "params": [ "enqueued_time" ] },
       {
        "type": "max",
        "params": []
       }
      ]
     ],
     "query": "SELECT \"enqueued_time\" FROM \"zuul-queue-status\" WHERE (\"pipeline\" = 'gate' AND \"queue\" = 'tripleo') AND $timeFilter"
    }
   ]
  },
  {
   "title": "RDO",
   "type": "graph",
   "gridPos": { "y": 10, "h": 5, "w": 6, "x": 4 },
   "yaxes": [
    { "format": "short", "label": "min result code" }
   ],
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" },
      {
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json",
       "key": "url",
       "condition": "AND"
      },
      { "operator": "=", "value": "560445", "key": "review", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "alias": "openstack-check (560445)",
     "select": [
      [
       { "type": "field", "params": [ "result_code" ] },
       {
        "type": "min",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" },
      {
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json",
       "key": "url",
       "condition": "AND"
      },
      { "operator": "=", "value": "567224", "key": "review", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "alias": "openstack-check (567224)",
     "select": [
      [
       { "type": "field", "params": [ "result_code" ] },
       {
        "type": "min",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" },
      {
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json",
       "key": "url",
       "condition": "AND"
      },
      { "operator": "=", "value": "564285", "key": "review", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "alias": "openstack-check (564285)",
     "select": [
      [
       { "type": "field", "params": [ "result_code" ] },
       {
        "type": "min",
        "params": []
       }
      ]
     ]
    },
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" },
      {
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json",
       "key": "url",
       "condition": "AND"
      },
      { "operator": "=", "value": "564291", "key": "review", "condition": "AND" }
     ],
     "measurement": "zuul-queue-status",
     "alias": "openstack-check (564291)",
     "select": [
      [
       { "type": "field", "params": [ "result_code" ] },
       {
        "type": "min",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RDO openstack-check noop failures",
   "type": "table",
   "gridPos": { "y": 10, "h": 5, "w": 12, "x": 10 },
   "targets": [
    {
     "tags": [
      { "operator": "=", "value": "openstack-check", "key": "pipeline" },
      {
       "operator": "=",
       "value": "https://review.rdoproject.org/zuul/status.json",
       "key": "url",
       "condition": "AND"
      }
     ],
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "type": "field", "params": [ "result_code" ] }
      ]
     ],
     "query": "SELECT \"job\", \"review\", \"patch_set\", \"result\" FROM \"zuul-queue-status\" WHERE result_code=-1 AND \"pipeline\" = 'openstack-check' AND \"url\" = 'https://review.rdoproject.org/zuul/status.json' AND $timeFilter AND (\"review\"='560445' OR \"review\"='567224' OR \"review\"='564285 ' OR \"review\"='564291' )",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] }
     ]
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "y": 15, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "Urgent bugs",
   "type": "table",
   "gridPos": { "y": 16, "h": 9, "w": 12, "x": 0 },
   "targets": [
    {
     "measurement": "urgent-bugs",
     "select": [
      [
       { "type": "field", "params": [ "title" ] }
      ],
      [
       { "type": "field", "params": [ "status" ] }
      ],
      [
       { "type": "field", "params": [ "link" ] }
      ]
     ],
     "query": "SELECT \"title\", \"status\", \"link\" FROM \"urgent-bugs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Openstack infra issues",
   "type": "table",
   "gridPos": { "y": 16, "h": 9, "w": 10, "x": 12 },
   "targets": [
    {
     "measurement": "openstack-infra-issues",
     "select": [
      [
       { "type": "field", "params": [ "issue" ] }
      ]
     ],
     "query": "SELECT \"issue\" FROM \"openstack-infra-issues\""
    }
   ]
  }
 ]
}