{
 "title": "Upstream and RDO promotions",
 "description": "Visualization of the Component and Integration Promotion Pipelines",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "TripleO-CI promotions",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'master' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'wallaby' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'victoria' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'ussuri' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\",  last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'stein' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, \"consistent_date\", last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'queens' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RDO promotions",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'master' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'victoria' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'ussuri' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'stein' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'rocky' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT release, distro, promotion_details, last(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'queens' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY release, \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 master tripleo ci ( current-tripleo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for master.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'master' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Master Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\", \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'baremetal' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cinder' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'clients' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cloudops' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'common' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'compute' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'glance' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'manila' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'network' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'octavia' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'security' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'swift' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tempest' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tripleo' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'ui' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'master' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'validation' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 master RDO ( current-tripleo-rdo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo-rdo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'master' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Master failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /master/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 Wallaby tripleo ci ( current-tripleo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for wallaby. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'wallaby' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallaby Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\", \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'baremetal' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cinder' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'clients' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cloudops' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'common' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'compute' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'glance' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'manila' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'network' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'octavia' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'security' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'swift' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tempest' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tripleo' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'ui' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'wallaby' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'validation' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 Wallaby RDO ( current-tripleo-rdo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo-rdo for wallaby. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'wallaby' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Master Promotions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Wallaby failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /wallaby/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 Victoria tripleo ci ( current-tripleo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for ussuri. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'victoria' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Victoria Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\", \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'baremetal' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cinder' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'clients' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cloudops' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'common' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'compute' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'glance' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'manila' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'network' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'octavia' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'security' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'swift' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tempest' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tripleo' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'ui' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'victoria' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'validation' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 Victoria RDO ( current-tripleo-rdo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo-rdo for ussuri. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'Victoria' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Victoria failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /victoria/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Ussuri Promotions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Promotions for CentOS-8 ussuri tripleo ci ( current-tripleo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for ussuri. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'ussuri' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ussuri Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\", \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'baremetal' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cinder' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'clients' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cloudops' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'common' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'compute' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'glance' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'manila' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'network' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'octavia' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'security' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'swift' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tempest' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tripleo' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'ui' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'validation' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 ussuri RDO ( current-tripleo-rdo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo-rdo for ussuri. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'ussuri' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ussuri failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /ussuri/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Older Releases Promotions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Promotions for CentOS-8 train tripleo ci ( current-tripleo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for ussuri. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Train CentOS-8 Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\", \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'baremetal' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cinder' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'clients' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'cloudops' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'common' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'compute' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'glance' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'manila' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'network' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'octavia' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'security' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\", last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'swift' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tempest' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'tripleo' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'ui' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select   \"component\",  \"repo_url\",  \"consistent_date\",  last(\"repo_hash\") from \"dlrn-promotion\" where (\"release\" = 'train' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8'  and \"component\" = 'validation' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-8 train RDO ( current-tripleo-rdo )",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for ussuri. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-8') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-7 train TripleO ( current-tripleo)",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for train. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-7 train RDO ( current-tripleo-rdo)",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for train. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'train' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Train failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /train/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-7 stein TripleO ( current-tripleo)",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for train. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'stein' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-7 stein RDO ( current-tripleo-rdo)",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for train. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'stein' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stein failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /stein/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-7 queens TripleO ( current-tripleo)",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for queens. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'queens' AND \"name\" = 'current-tripleo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions for CentOS-7 queens RDO ( current-tripleo-rdo)",
   "type": "graph",
   "description": "Bars represent successful promotions to current-tripleo for queens. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short", "label": "Number of Promotions" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"repo_hash\") FROM \"dlrn-promotion\" WHERE (\"release\" = 'queens' AND \"name\" = 'current-tripleo-rdo' AND \"distro\" = 'CentOS-7') AND $timeFilter GROUP BY time(24h), \"name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queens failing periodic jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 164 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"log_link\", \"duration\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" =~ /periodic/ AND \"type\" = 'rdo' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /queens/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}