USE rrcockpit;

CREATE TABLE IF NOT EXISTS rr_pass_tests (
    id MEDIUMINT  NOT NULL AUTO_INCREMENT,
    Branch VARCHAR(255) NOT NULL,
    Testname VARCHAR(255) NOT NULL,
    Result VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

TRUNCATE TABLE rr_pass_tests;

LOAD DATA LOCAL INFILE '/tmp/pass.csv' \n
INTO TABLE rr_pass_tests \n
FIELDS TERMINATED BY ',' \n
LINES TERMINATED BY '\n';
