{
 "title": "Centos 9 and Centos 8 Comparison - wallaby",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Promotions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Centos 9 Promotions",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select release,  promo_name, distro, latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"promo_name\" = 'current-tripleo' AND \"distro\" = 'centos-9' AND \"release\" = 'wallaby') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Centos 8 Promotions",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select release,  promo_name, distro, latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"promo_name\" = 'current-tripleo' AND \"distro\" = 'centos-8' AND \"release\" = 'wallaby') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failing jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Centos 9 - Failing integration jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'integration' AND \"release\" = 'wallaby' and \"job_name\" =~ /centos-9/ and \"status\" = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Centos 8 - Failing integration jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'integration' AND \"release\" = 'wallaby' and \"job_name\" =~ /centos-8/ and \"status\" = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Passing jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Centos 9 - Passing integration jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'integration' AND \"release\" = 'wallaby' and \"job_name\" =~ /centos-9/ and \"status\" != '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Centos 8 - Passing integration jobs",
   "type": "table-old",
   "description": "List of the latest failing integration / promotion  jobs.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'integration' AND \"release\" = 'wallaby' and \"job_name\" =~ /centos-8/ and \"status\" != '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Centos 9 Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'baremetal' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'cinder' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'clients' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'cloudops' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'common' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'compute' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'glance' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'manila' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'network' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'octavia' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'security' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'swift' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'tempest' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'tripleo' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'ui' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'validation' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Centos 8 Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'baremetal' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'cinder' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'clients' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'cloudops' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'common' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'compute' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'glance' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'manila' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'network' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'octavia' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'security' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'swift' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'tempest' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'tripleo' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'ui' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'wallaby' AND \"component\" = 'validation' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-8' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}