{
 "title": "Ceph Jobs and Promotions",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Ceph Nightly Jobs ",
   "type": "table-old",
   "description": "Click on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'periodic' AND  \"job_name\" =~ /.*ceph-nightly.*/)  AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Ceph Nightly CI Stats",
   "type": "grafana-piechart-panel",
   "description": "Percentage of Ceph nightly jobs that are passing vs failing.",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"type\" = 'upstream' AND \"pipeline\"='periodic' AND  \"job_name\" =~ /.*ceph-nightly.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "select count(\"result_num\") from \"build\" where ( \"passed\" = 'False' and \"type\" = 'upstream' and \"pipeline\" = 'periodic' and result !~ /SKIPPED|NODE_FAILURE|TIMED_OUT|CANCELED|ABORTED|RETRY|RETRY_LIMIT|LOST|ERROR/  AND  \"job_name\" =~ /.*ceph-nightly.*/) and $timeFilter\n",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Ceph Daemon Promotion Pipeline - Scenario Jobs - Master",
   "type": "table-old",
   "description": "Click on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND  \"job_name\" =~ /.*ceph-updates.*-master$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Ceph Daemon - Latest Promotions - Master",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "  SELECT \"log_link\", \"duration\", \"result\" FROM \"build\" WHERE (\"result\" = 'SUCCESS' AND \"type\" = 'rdo' AND  \"job_name\" =~ /.*promote-ceph-daemon.*-master$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "wallaby" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Ceph Daemon Promotion Pipeline - Scenario Jobs - Wallaby",
   "type": "table-old",
   "description": "Click on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND  \"job_name\" =~ /.*ceph-updates.*-wallaby$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Ceph Daemon - Latest Promotions - Wallaby",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "  SELECT \"log_link\", \"duration\", \"result\" FROM \"build\" WHERE (\"result\" = 'SUCCESS' AND \"type\" = 'rdo' AND  \"job_name\" =~ /.*promote-ceph-daemon.*-wallaby$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "wallaby" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  }
 ]
}