{
 "title": "Component Pipeline Zed",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   { "name": "releases", "label": "Release", "query": "zed" },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo"
   },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  {
   "title": "TripleO-CI promotions",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select release,  promo_name, distro, latest_build_date, promotion_details, aggregate_hash from \"dlrn-promotion\" where (\"promo_name\" = 'current-tripleo' AND \"distro\" = 'centos-9' AND \"release\" = 'zed') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select release,  promo_name, distro, latest_build_date, promotion_details, aggregate_hash from \"dlrn-promotion\" where (\"promo_name\" = 'current-tripleo-rdo' AND \"distro\" = 'centos-9' AND \"release\" = 'zed') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "zed Components: Days since last promotion",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'baremetal' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'cinder' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'clients' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'cloudops' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'common' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'compute' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'glance' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'manila' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'network' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'octavia' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'security' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'swift' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'tempest' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'tripleo' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'ui' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select component,  promo_name,  latest_build_date, promotion_details, last(aggregate_hash) from \"dlrn-promotion\" where (\"release\" = 'zed' AND \"component\" = 'validation' AND \"promo_name\" = 'promoted-components' AND \"distro\" = 'centos-9' ) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Periodic jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Baremetal Component",
   "type": "table-old",
   "description": "List of the latest component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'baremetal') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Baremetal promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'baremetal') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Cinder Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'cinder') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cinder promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'cinder') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Clients Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'clients') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'clients') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Common Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'common') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Common promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'common') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "CloudOps Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'cloudops') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CloudOps promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 50 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'cloudops') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Compute Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 58 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'compute') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Compute promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 58 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'compute') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Glance Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 66 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'glance') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Glance promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 66 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'glance') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Manila Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 74 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'manila') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Manila promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 74 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'manila') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Network Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 82 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'network') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 82 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'network') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Octavia Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 90 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'octavia') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Octavia promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 90 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'octavia') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Security Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 98 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'security') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Security promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 98 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'security') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Swift Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 106 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'swift') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swift promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 106 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'swift') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Tempest Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 114 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'tempest') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tempest promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 114 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'tempest') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "TripleO Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 122 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'tripleo') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TripleO promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 122 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'tripleo') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "UI Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 130 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'ui') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UI promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 130 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'ui') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  },
  {
   "title": "Validation Component",
   "type": "table-old",
   "description": "List of the latest failing component jobs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 138 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"job_name\",\"status\",\"criteria\",\"logs\",\"duration\",\"failure_reason\",\"test_hash\"  FROM \"autogen\".\"jobs_result\" WHERE (\"job_type\" = 'component' AND \"release\" = 'zed' AND \"component\" = 'validation') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validations promotions",
   "type": "table-old",
   "description": "Bars represent successful promotions to current-tripleo for zed. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 138 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select  promotion_details,  promo_name, commit_hash, distro_hash  from \"dlrn-promotion\" where (\"release\" = 'zed' and \"promo_name\" = 'promoted-components' and \"distro\" = 'centos-9' and \"component\" = 'validation') ",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "zed" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-9" }
     ]
    }
   ]
  }
 ]
}