{
 "title": "Component Pipeline Ussuri",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   {
    "name": "releases",
    "label": "Release",
    "query": "master,train,stein,rocky,queens"
   },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo"
   },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  { "title": "Periodic jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Baremetal",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-baremetal.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Baremetal promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'baremetal') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-cinder.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Cinder promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'cinder') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-clients.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Clients promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'clients') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Common",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 25 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-common.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Common promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'common') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "CloudOps",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 33 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-cloudops.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "CloudOps promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'cloudops') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Compute",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 41 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-compute.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Compute promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 41 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'compute') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Glance",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 49 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-glance.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Glance promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 49 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'glance') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Manila",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 57 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-manila.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Manila promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 57 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'manila') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 65 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-network.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Network promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 65 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'network') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "Octavia",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 73 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-octavia.*-ussuri/ and \"type\"='rdo') AND $timeFilter\n",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Octavia promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 73 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'octavia') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": " Security",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 81 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-security.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Security promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 81 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'security') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": " Swift",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 89 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-swift.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Swift promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 89 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'swift') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": " Tempest",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 97 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-tempest.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "Tempest promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 97 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'tempest') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": " TripleO",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 105 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-tripleo.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "TripleO promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 105 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'tripleo') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  },
  {
   "title": "UI",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 113 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"job_name\" =~ /periodic-tripleo-ci-centos-8.*-ui.*-ussuri/and \"type\"='rdo') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-periodic-24hr" },
      {
       "condition": "OR",
       "key": "pipeline",
       "operator": "=",
       "value": "openstack-periodic-latest-released"
      },
      { "condition": "OR", "key": "pipeline", "operator": "=", "value": "openstack-periodic-master" }
     ]
    }
   ]
  },
  {
   "title": "UI promotions",
   "type": "table",
   "description": "Bars represent successful promotions to current-tripleo for master. Default time is the last 2 weeks.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 113 },
   "targets": [
    {
     "alias": "repo",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dlrn-promotion",
     "query": "select count(\"repo_hash\") as \"count\", last(\"repo_hash\") as \"repo\", last(\"repo_url\") as \"repo_url\" from \"dlrn-promotion\" where (\"release\" = 'ussuri' and \"name\" = 'promoted-components' and \"distro\" = 'CentOS-8' and \"component\" = 'ui') group by time(24h), *\n",
     "select": [
      [
       { "params": [ "repo_hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "current-tripleo" },
      { "condition": "AND", "key": "distro", "operator": "=", "value": "CentOS-7" }
     ]
    }
   ]
  }
 ]
}