{
 "title": "Non-Voting Jobs",
 "description": "A dynamic list of non-voting jobs per branch",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MASTER: Projects with Non Voting Jobs in TripleO",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\")  FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"job_name\" =~ /.*tripleo-.*/ AND \"voting\" = 'False' AND \"branch\" = 'master' ) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MASTER: Non Voting Jobs in TripleO",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\")  FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"job_name\" =~ /.*tripleo-.*/ AND \"voting\" = 'False' AND \"branch\" = 'master' ) AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TRAIN: Projects with Non Voting Jobs in TripleO",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\")  FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"job_name\" =~ /.*tripleo-.*/ AND \"voting\" = 'False' AND \"branch\" = 'stable/train' ) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TRAIN: Non Voting Jobs in TripleO",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\")  FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"job_name\" =~ /.*tripleo-.*/ AND \"voting\" = 'False' AND \"branch\" = 'stable/train' ) AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}