{
 "title": "Openstack Ansible collections",
 "description": "Data related to ansible openstack collections project",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Openstack Ansible modules check jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "build",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "project",
       "operator": "=",
       "value": "openstack/ansible-collections-openstack"
      },
      { "condition": "AND", "key": "pipeline", "operator": "<>", "value": "periodic" },
      { "condition": "AND", "key": "result", "operator": "<>", "value": "SKIPPED" }
     ]
    }
   ]
  },
  {
   "title": "Openstack Ansible modules periodic jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "build",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "project",
       "operator": "=",
       "value": "openstack/ansible-collections-openstack"
      },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "periodic" }
     ]
    }
   ]
  },
  {
   "title": "Issues",
   "type": "table",
   "description": "Bugs, tasks for openstack collections",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "story",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ],
      [
       { "params": [ "link" ], "type": "field" }
      ],
      [
       { "params": [ "current" ], "type": "field" }
      ],
      [
       { "params": [ "updated" ], "type": "field" }
      ],
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "not_started" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patch for collections",
   "type": "table",
   "description": "Patches submitted for Openstack Ansible collections",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "measurement": "patch",
     "select": [
      [
       { "params": [ "owner" ], "type": "field" }
      ],
      [
       { "params": [ "link" ], "type": "field" }
      ],
      [
       { "params": [ "updated" ], "type": "field" }
      ],
      [
       { "params": [ "mergeable" ], "type": "field" }
      ],
      [
       { "params": [ "id" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "project",
       "operator": "=",
       "value": "openstack/ansible-collections-openstack"
      }
     ]
    }
   ]
  }
 ]
}