{
 "title": "OSP Dependency Pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ansible",
   "type": "table-old",
   "description": "Running list of *upstream* periodic jobs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"type\" = 'internal' AND \"pipeline\" = 'openstack-dependencies-latest_ansible') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "periodic" }
     ]
    }
   ]
  },
  {
   "title": "Intro",
   "type": "text",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 6 },
   "options": {
    "content": "\n# OSP Dependency pipeline\n\nTripleO-CI takes the lastest good build of OSP and deploys with specific OSP rpm dependencies of unknown quality.  e.g. take the very latest builds of ansible and inject them into a known working build.\n\nPending releases for Example:\n\n- RHEL\n- Container Tools\n- Ansible releases\n- Ceph re\n- Openvswitch\n- Pacemaker\n\n\n"
   }
  },
  {
   "title": "RHEL",
   "type": "table-old",
   "description": "Running list of *upstream* periodic jobs",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"type\" = 'internal' AND \"pipeline\" = 'openstack-dependencies-rhel_u_next') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "periodic" }
     ]
    }
   ]
  },
  {
   "title": "Container_Tools",
   "type": "table-old",
   "description": "Running list of *upstream* periodic jobs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"type\" = 'internal' AND \"pipeline\" = 'openstack-dependencies-container_tools') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "periodic" }
     ]
    }
   ]
  },
  {
   "title": "OpenVSwitch",
   "type": "table-old",
   "description": "Running list of *upstream* periodic jobs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\" FROM \"build\" WHERE (\"type\" = 'internal' AND \"pipeline\" = 'openstack-dependencies-openvswitch') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "periodic" }
     ]
    }
   ]
  }
 ]
}