{
 "title": "Puppet Promotion Pipelines",
 "description": "This dashboard shows status of Master, Zed, Yoga, Xena, Wallaby puppet promotion pipelines",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Promotions Antelope",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-antelope-promote-*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Zed",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-zed-promote-*/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Yoga CS9",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-yoga-promote-*/ AND \"job_name\" =~ /stream-9/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Yoga CS8",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-yoga-promote-*/ AND \"job_name\" =~ /stream-8/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Xena CS9",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-xena-promote-*/ AND \"job_name\" =~ /stream-9/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Xena CS8",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-xena-promote-*/ AND \"job_name\" =~ /stream-8/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Wallaby CS9",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-wallaby-promote-*/ AND \"job_name\" =~ /stream-9/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Promotions Wallaby CS8",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT \"job_name\", \"result\", \"duration\", \"pipeline\",  \"log_url\" FROM \"build\" WHERE (\"project\" = 'rdoinfo' AND \"job_name\" =~ /weirdo-wallaby-promote-*/ AND \"job_name\" =~ /stream-8/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}