{
 "title": "Security Cockpit",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   {
    "name": "releases",
    "label": "Release",
    "query": "master,train,stein,rocky,queens"
   },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo"
   },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream Zuul queue",
   "type": "singlestat",
   "description": "Upstream zuul *gate* queue.  The time a given patch will wait before running the upstream gate.\n\nClick on the links below to go to the zuul build status.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "Upstream gate jobs",
   "type": "singlestat",
   "description": "Number of failing upstream *gate* jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"pipeline\" = 'gate' AND \"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-*ipa.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Upstream failing gate jobs",
   "type": "table",
   "description": "A running list of failing upstream *gate* jobs. By default this will show the last 3 days.\n\nClick on individual jobs to go to the logs or to the gerrit change.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"cloud\", \"region\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" = 'gate' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo.*ipa.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "cloud" ], "type": "field" }
      ],
      [
       { "params": [ "region" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Useful Links",
   "type": "text",
   "description": "This is a place to keep some notes and links to current etherpads for ruck rovers.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "[ruck rover etherpad](https://hackmd.io/team/rh-openstack-ci?nav=search&q=ruck_rover) [rhos-release](http://rhos-release.virt.bos.redhat.com:3030/rhosp) "
  },
  {
   "title": "Security MASTER gate",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'master'  AND \"pipeline\" = 'gate') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'master'  AND \"pipeline\" = 'gate') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'master'  AND \"pipeline\" = 'gate') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "MASTER IPA check",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPA PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'master'  AND \"pipeline\" = 'check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "IPA FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'master'  AND \"pipeline\" = 'check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "IPA TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'master'  AND \"pipeline\" = 'check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "MASTER 039 check",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPA PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/ AND \"branch\" = 'master' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "IPA FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/ AND \"branch\" = 'master' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "IPA TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*039.*/ AND \"branch\" = 'master'  ) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "USSURI IPA check",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPA PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'stable/ussuri'  AND \"pipeline\" = 'check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "IPA FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'stable/ussuri'  AND \"pipeline\" = 'check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "IPA TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*ipa.*/ AND \"branch\" = 'stable/ussuri'  AND \"pipeline\" = 'check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "USSURI 039 check",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPA PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/ AND \"branch\" = 'stable/ussuri' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "IPA FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/ AND \"branch\" = 'stable/ussuri' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "IPA TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"job_name\" =~ /tripleo-.*039.*/ AND \"branch\" = 'stable/ussuri'  ) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Upstream MASTER  jobs",
   "type": "table",
   "description": "Running list of MASTER upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'master' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'master' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream USSURI  jobs",
   "type": "table",
   "description": "Running list of USSURI upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/ussuri' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/ussuri' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream TRAIN  jobs",
   "type": "table",
   "description": "Running list of TRAIN upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/train' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/train' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream STEIN  jobs",
   "type": "table",
   "description": "Running list of STEIN upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/stein' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/stein' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream ROCKY  jobs",
   "type": "table",
   "description": "Running list of ROCKY upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/rocky' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/rocky' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream ROCKY  jobs",
   "type": "table",
   "description": "Running list of ROCKY upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/queens' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*ipa.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"branch\" = 'stable/queens' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-.*039.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  }
 ]
}