{
 "title": "Upstream Heat",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   {
    "name": "releases",
    "label": "Release",
    "query": "master,train,stein,rocky,queens"
   },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo"
   },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  {
   "title": "Master Branch all jobs",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"branch\" = 'master' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"branch\" = 'master' AND \"project\" = 'openstack/heat' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"branch\" = 'master' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Victoria Branch all jobs",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"branch\" = 'stable/victoria' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"branch\" = 'stable/victoria' AND \"project\" = 'openstack/heat' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"branch\" = 'stable/victoria' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Train Branch all jobs",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"branch\" = 'stable/train' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"branch\" = 'stable/train' AND \"project\" = 'openstack/heat' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"branch\" = 'stable/train' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "All upstream jobs",
   "type": "singlestat",
   "description": "Number of failing upstream jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND  \"result\" != 'RETRY' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Check jobs",
   "type": "singlestat",
   "description": "Number of failing upstream jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"pipeline\" = 'check' AND \"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND  \"result\" != 'RETRY' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Gate jobs",
   "type": "singlestat",
   "description": "Number of failing upstream jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"pipeline\" = 'gate' AND \"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND  \"result\" != 'RETRY' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Periodic jobs",
   "type": "singlestat",
   "description": "Number of failing upstream Periodic jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"pipeline\" =~ /periodic.*/  AND \"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND  \"result\" != 'RETRY' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Zuul queue",
   "type": "singlestat",
   "description": "Upstream zuul *gate* queue.  The time a given patch will wait before running the upstream gate.\n\nClick on the links below to go to the zuul build status.",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "Upstream failing gate jobs",
   "type": "table-old",
   "description": "A running list of failing upstream jobs. By default this will show the last 3 days.\n\nClick on individual jobs to go to the logs or to the gerrit change.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"pipeline\", \"change\", \"log_link\", \"duration\",  \"result\", \"sova_reason\" as \"Failure Cause\"  FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND  \"result\" != 'RETRY' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "cloud" ], "type": "field" }
      ],
      [
       { "params": [ "region" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Upstream CI stats",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"project\" = 'openstack/heat')  AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"project\" = 'openstack/heat')AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Periodic CI stats",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *periodic* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"pipeline\"='periodic'  AND \"result\" != 'NODE_FAILURE' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"pipeline\"='periodic' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"pipeline\"='periodic' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Upstream jobs failed in RETRY",
   "type": "singlestat",
   "description": "Number of failing upstream *gate* jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"pipeline\" = 'gate' AND \"passed\" = 'False' AND \"result\" = 'RETRY')  AND \"project\" = 'openstack/heat' AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Master Branch, Upstream Check",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"branch\" = 'master'  AND \"pipeline\" = 'check') AND \"project\" = 'openstack/heat' AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"branch\" = 'master' AND \"pipeline\" = 'check' ) AND \"project\" = 'openstack/heat' AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"branch\" = 'master'  AND \"pipeline\" = 'check') AND \"project\" = 'openstack/heat' AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Upstream failing jobs in RETRY",
   "type": "table-old",
   "description": "A running list of failing upstream that hit RETRY's",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\",  \"pipeline\", \"log_link\", \"duration\", \"result\", \"sova_reason\" as \"Failure Cause\"  FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False'  AND \"result\" = 'RETRY' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "cloud" ], "type": "field" }
      ],
      [
       { "params": [ "region" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Upstream periodic jobs",
   "type": "table-old",
   "description": "Running list of *upstream* periodic jobs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"log_link\", \"duration\", \"result\", \"result_num\", \"sova_reason\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'periodic' AND \"project\" = 'openstack/heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "periodic" }
     ]
    }
   ]
  },
  {
   "title": "Upstream TripleO tox and molecule jobs",
   "type": "table-old",
   "description": "Running list of all upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"pipeline\", \"voting\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /.*molecule-.*/ OR \"job_name\" =~ /.tox.*/ ) AND \"project\" = 'openstack/heat' AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  { "title": "Zuul jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "CI stats weekly check jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PASS",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'check') AND \"project\" = 'openstack/heat' AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "check" }
     ]
    },
    {
     "alias": "FAIL",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'check') AND \"project\" = 'openstack/heat' AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "check" }
     ]
    }
   ]
  },
  {
   "title": "CI stats weekly gate jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PASS",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'gate') AND \"project\" = 'openstack/heat' AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" }
     ]
    },
    {
     "alias": "FAIL",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'gate') AND \"project\" = 'openstack/heat' AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" }
     ]
    }
   ]
  }
 ]
}