{
 "title": "Vexxhost",
 "description": "Monitoring of vexxhost",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdb_filter", "label": "influxdb_filter" }
  ]
 },
 "panels": [
  {
   "title": "Vexxhost RDO promotion jobs",
   "type": "table",
   "description": "A running list of RDO jobs that are in the  openstack-periodic-24hr openstack-periodic-latest-released zuul pipelines.\n\nNOTE: this does *not* necessarily mean the jobs here listed here are also  in the promotion criteria. \n\nUse the links below to see the RDO zuul builds or the promotion criteria.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "build",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "cloud", "operator": "=", "value": "vexxhost-nodepool-tripleo" },
      { "condition": "AND", "key": "pipeline", "operator": "=~", "value": "/.*openstack-periodic.*/" }
     ]
    }
   ]
  },
  {
   "title": "Vexxhost RDO check jobs",
   "type": "table",
   "description": "A running list of RDO jobs that are in the  openstack-periodic-24hr openstack-periodic-latest-released zuul pipelines.\n\nNOTE: this does *not* necessarily mean the jobs here listed here are also  in the promotion criteria. \n\nUse the links below to see the RDO zuul builds or the promotion criteria.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "build",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cloud", "operator": "=", "value": "vexxhost-nodepool-tripleo" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "openstack-check" }
     ]
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CREATE_COMPLETE",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "create_complete" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CREATE_FAILED",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "create_failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CREATE_IN_PROGRESS",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "create_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DELETE_COMPLETE",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "delete_complete" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DELETE_FAILED",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "delete_failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DELETE_IN_PROGRESS",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "delete_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Problematic stacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of stacks" }
   ],
   "targets": [
    {
     "alias": "Old stacks",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "old_stacks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed to delete",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "delete_failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of problematic heat stacks",
   "type": "graph",
   "description": "This shows the number of heat stacks in CREATE_FAILED, DELETE_FAILED, ERROR",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of stacks" }
   ],
   "targets": [
    {
     "alias": "Old stacks",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "old_stacks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed to delete",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "delete_failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instances types",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BMC node",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "bmc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Undercloud",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "undercloud" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "OVB BM node",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "ovb-node" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Other",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "other" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-servers",
     "select": [
      [
       { "params": [ "ACTIVE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ACTIVE" ], "type": "alias" }
      ],
      [
       { "params": [ "BUILD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BUILD" ], "type": "alias" }
      ],
      [
       { "params": [ "DELETED" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DELETED" ], "type": "alias" }
      ],
      [
       { "params": [ "ERROR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ERROR" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU cores",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-perf",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-perf",
     "select": [
      [
       { "params": [ "ram" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Servers",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-perf",
     "select": [
      [
       { "params": [ "instances" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ports in DOWN state",
   "type": "graph",
   "description": "Ports in DOWN state in RDO cloud, which should be deleted by cleaning scripts.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Ports in DOWN" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vexxhost-perf",
     "select": [
      [
       { "params": [ "ports_down" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RDO node failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Number of failures" }
   ],
   "targets": [
    {
     "alias": "Failures every 30 minutes",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" }
     ],
     "measurement": "build",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rdo" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "cloud", "operator": "=", "value": "vexxhost-nodepool-tripleo" }
     ]
    }
   ]
  }
 ]
}