{
 "title": "Jobs Exploration",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  {
   "title": "Last jobs",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result_num\", \"cloud\", \"region\", \"voting\", \"pipeline\",  \"result\", \"sova_reason\" FROM \"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "cloud" ], "type": "field" }
      ],
      [
       { "params": [ "region" ], "type": "field" }
      ],
      [
       { "params": [ "sova_reason" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CI stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Jobs Frequency",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\") FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream') AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "upstream" }
     ]
    }
   ]
  },
  {
   "title": "GATE: Jobs Frequency",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\") FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"pipeline\" = 'gate' ) AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "upstream" }
     ]
    }
   ]
  },
  {
   "title": "FAILED: Jobs Frequency",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\") FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"result\" != 'SUCCESS' ) AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "upstream" }
     ]
    }
   ]
  },
  {
   "title": "FAILED GATE: Jobs Frequency",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\") FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"result\" != 'SUCCESS'  AND \"pipeline\" = 'gate' ) AND $timeFilter GROUP BY \"job_name\"",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "upstream" }
     ]
    }
   ]
  },
  {
   "title": "FAILED: Jobs Frequency by Project",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "job_name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\"), mean(\"duration\"), max(\"duration\"), mean(\"container_prep_time_u\"), max(\"container_prep_time_u\"), sum(\"duration\"), sum(\"result_num\")*100/count(\"result_num\") FROM \"autogen\".\"build\" WHERE (\"type\" = 'upstream' AND \"result\" != 'SUCCESS' ) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "upstream" }
     ]
    }
   ]
  },
  {
   "title": "Jobs Frequency Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of builds every 30 minutes",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" }
     ],
     "measurement": "build",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs Duration Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Build duration media every 30 minutes",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" }
     ],
     "measurement": "build",
     "query": "SELECT median(\"duration\") FROM \"build\" WHERE $timeFilter GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job build duration per cloud",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "dtdurations", "label": "durastion" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT median(\"duration\") FROM \"build\" WHERE $timeFilter GROUP BY \"cloud\", \"region\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job builds count per cloud",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"end\") FROM \"build\" WHERE $timeFilter GROUP BY \"cloud\", \"region\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TIMED OUT Job count per cloud",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"end\") FROM \"build\" WHERE ( \"result\" = 'TIMED_OUT' ) AND  $timeFilter GROUP BY \"cloud\", \"region\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FAILED Job count per cloud",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"end\") FROM \"build\" WHERE (\"result\" != 'TIMED_OUT' AND \"result\" != 'SKIPPED' AND \"passed\" = 'False' ) AND  $timeFilter GROUP BY \"cloud\", \"region\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Passing Job count per cloud",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"end\") FROM \"build\" WHERE (\"passed\" = 'True' ) AND  $timeFilter GROUP BY \"cloud\", \"region\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream total job executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "none", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE ( \"result\" != 'NODE_FAILURE'  and \"type\" = 'upstream' ) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "3rd party total job executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "none", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloud" ], "type": "tag" },
      { "params": [ "region" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE ( \"result\" != 'NODE_FAILURE'  and \"type\" = 'rdo' ) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Time: tripleo-ci-centos-7-containers-multinode",
   "type": "graph",
   "description": "job run time for  tripleo-ci-centos-7-containers-multinode",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Build duration media every 30 minutes",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" }
     ],
     "measurement": "build",
     "query": "SELECT max(\"duration\")  FROM \"build\" WHERE  (\"job_name\") = 'tripleo-ci-centos-7-containers-multinode'  GROUP BY time(30m)\n",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  }
 ]
}