{
 "title": "Third Party Dependency Check",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   {
    "name": "releases",
    "label": "Release",
    "query": "master,train,stein,rocky,queens"
   },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo"
   },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream Zuul queue",
   "type": "singlestat",
   "description": "Upstream zuul *gate* queue.  The time a given patch will wait before running the upstream gate.\n\nClick on the links below to go to the zuul build status.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zuul-queue-status",
     "query": "SELECT max(\"enqueued_time\") FROM \"zuul-queue-status\" WHERE (\"pipeline\" = 'github-check') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "Upstream CI stats",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'github-check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"pipeline\" = 'github-check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"pipeline\" = 'github-check') AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "github-check failing jobs",
   "type": "table",
   "description": "A running list of failing github-check *check* jobs. By default this will show the last 3 days.\n\nClick on individual jobs to go to the logs or to the gerrit change.",
   "gridPos": { "h": 10, "w": 14, "x": 9, "y": 1 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"cloud\", \"region\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" = 'github-check' AND \"result\" != 'NODE_FAILURE') AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "cloud" ], "type": "field" }
      ],
      [
       { "params": [ "region" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Useful Links",
   "type": "text",
   "description": "This is a place to keep some notes and links to current etherpads for ruck rovers.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "[Design](https://tree.taiga.io/project/tripleo-ci-board/epic/1271), [Documentation](https://docs.openstack.org/tripleo-docs/latest/ci/third_party_dependencies_ci.html)"
  },
  {
   "title": "RDO github-check pipeline",
   "type": "table",
   "description": "Running list of all jobs running in the RDO github-check pipeline\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'github-check') AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "RDO github-manual pipeline",
   "type": "table",
   "description": "Running list of all jobs running in the RDO github-manual pipeline\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'github-manual') AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  {
   "title": "RDO openstack-periodic-weekend pipeline",
   "type": "table",
   "description": "Running list of all jobs running in the RDO openstack-periodic-weekend\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'rdo' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'openstack-periodic-weekend') AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  { "title": "Bugs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Third party dependency bugs marked \"depcheck\" ",
   "type": "table",
   "description": "List of TripleO promotion-blocker bugs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "measurement": "launchpad-bug",
     "rawSql": "SELECT id, status, tag, description, link from rr_bugs where (tag LIKE \"%depcheck%\")",
     "slimit": "1",
     "tags": [
      { "key": "tag", "operator": "=", "value": "promotion-blocker" }
     ]
    }
   ]
  },
  {
   "title": "Promotion blockers",
   "type": "table",
   "description": "List of TripleO promotion-blocker bugs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "measurement": "launchpad-bug",
     "rawSql": "SELECT id, status, tag, description, link from rr_bugs where (tag LIKE \"%promotion-blocker%\" AND tag LIKE \"%upgrade%\")",
     "slimit": "1",
     "tags": [
      { "key": "tag", "operator": "=", "value": "promotion-blocker" }
     ]
    }
   ]
  },
  { "title": "Zuul jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "github-check stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PASS",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'github-check') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "check" }
     ]
    },
    {
     "alias": "FAIL",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'github-check' ) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "check" }
     ]
    }
   ]
  },
  {
   "title": "Check voting  jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "alias": "PASSED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result\") FROM \"build\" WHERE (\"pipeline\" = 'github-check' AND \"passed\" = 'True' AND \"voting\" = 'True') AND $timeFilter GROUP BY time(30m) fill(none)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "voting", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "FAILED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result\") FROM \"build\" WHERE (\"pipeline\" = 'github-check' AND \"passed\" = 'False' AND \"voting\" = 'True') AND $timeFilter GROUP BY time(30m) fill(none)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "voting", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "github-check  jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "alias": "PASSED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result\") FROM \"build\" WHERE (\"pipeline\" = 'github-check' AND \"passed\" = 'True') AND $timeFilter GROUP BY time(30m) fill(none)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "FAILED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result\") FROM \"build\" WHERE (\"pipeline\" = 'github-check' AND \"passed\" = 'False') AND $timeFilter GROUP BY time(30m) fill(none)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" }
     ]
    }
   ]
  }
 ]
}