{
 "title": "Upgrades Cockpit",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "launchpad_tags", "label": "Launchpad tags to show", "query": "alert, promotion-blocker" },
   {
    "name": "releases",
    "label": "Release",
    "query": "master,train,stein,rocky,queens"
   },
   {
    "name": "promotion_names",
    "query": "current-tripleo, current-tripleo-rdo"
   },
   { "name": "influxdb_filter", "label": "Influxdb filter" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream Zuul queue",
   "type": "singlestat",
   "description": "Upstream zuul *gate* queue.  The time a given patch will wait before running the upstream gate.\n\nClick on the links below to go to the zuul build status.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zuul-queue-status",
     "select": [
      [
       { "params": [ "enqueued_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "tripleo" }
     ]
    }
   ]
  },
  {
   "title": "Upstream gate jobs",
   "type": "singlestat",
   "description": "Number of failing upstream *gate* jobs in the last 24 hours.\n\nClick on links below to go to the source zuul builds status.",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"pipeline\" = 'gate' AND \"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Upstream CI stats",
   "type": "grafana-piechart-panel",
   "description": "Percentage of upstream  *gate and check* jobs that are passing vs failing vs timing out.\n\n",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PASS",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    },
    {
     "alias": "FAIL",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" != 'TIMED_OUT' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "TIMED_OUT" }
     ]
    },
    {
     "alias": "TIMED_OUT",
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"result\" = 'TIMED_OUT' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "TIMED_OUT" }
     ]
    }
   ]
  },
  {
   "title": "Upstream failing gate jobs",
   "type": "table",
   "description": "A running list of failing upstream *gate* jobs. By default this will show the last 3 days.\n\nClick on individual jobs to go to the logs or to the gerrit change.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"cloud\", \"region\", \"result\" FROM \"autogen\".\"build\" WHERE (\"passed\" = 'False' AND \"pipeline\" = 'gate' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "cloud" ], "type": "field" }
      ],
      [
       { "params": [ "region" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" }
     ]
    }
   ]
  },
  {
   "title": "Useful Links",
   "type": "text",
   "description": "This is a place to keep some notes and links to current etherpads for ruck rovers.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "[ruck rover etherpad](https://etherpad.openstack.org/p/ruckroversprint19) [rhos-release](http://rhos-release.virt.bos.redhat.com:3030/rhosp) [sova](http://cistatus.tripleo.org/)"
  },
  {
   "title": "Upstream last jobs",
   "type": "table",
   "description": "Running list of all upstream jobs including *check* and *gate* queues.\n\nClick on individual job names to go to logs or on the patch number to see the gerrit review.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT \"branch\", \"change\", \"log_link\", \"duration\", \"result\", \"result_num\", \"voting\" FROM \"build\" WHERE (\"result\" != 'SKIPPED' AND \"type\" = 'upstream' AND \"result\" != 'NODE_FAILURE' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter GROUP BY \"project\"",
     "select": [
      [
       { "params": [ "branch" ], "type": "field" }
      ],
      [
       { "params": [ "change" ], "type": "field" }
      ],
      [
       { "params": [ "log_link" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "result" ], "type": "field" }
      ],
      [
       { "params": [ "result_num" ], "type": "field" }
      ],
      [
       { "params": [ "voting" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "!=", "value": "SKIPPED" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "job_name", "operator": "=~", "value": "/.*tripleo-.*/" },
      { "condition": "OR", "key": "job_name", "operator": "=~", "value": "/.*molecule.*/" }
     ]
    }
   ]
  },
  { "title": "Bugs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Upgrade bugs marked \"Alert\" ( CI team monitoring )",
   "type": "table",
   "description": "List of TripleO promotion-blocker bugs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "measurement": "launchpad-bug",
     "rawSql": "SELECT id, status, tag, description, link from rr_bugs where (tag LIKE \"%alert%\" and tag LIKE \"%upgrade%\")",
     "slimit": "1",
     "tags": [
      { "key": "tag", "operator": "=", "value": "promotion-blocker" }
     ]
    }
   ]
  },
  {
   "title": "Promotion blockers",
   "type": "table",
   "description": "List of TripleO promotion-blocker bugs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "measurement": "launchpad-bug",
     "rawSql": "SELECT id, status, tag, description, link from rr_bugs where (tag LIKE \"%promotion-blocker%\" AND tag LIKE \"%upgrade%\")",
     "slimit": "1",
     "tags": [
      { "key": "tag", "operator": "=", "value": "promotion-blocker" }
     ]
    }
   ]
  },
  {
   "title": "all bugs tagged with \"upgrade\" under 365 days old",
   "type": "table",
   "description": "List of TripleO upgrade bugs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "measurement": "launchpad-bug",
     "rawSql": "SELECT id, status, tag, description, link from rr_bugs where (tag LIKE \"%upgrade%\")",
     "slimit": "1",
     "tags": [
      { "key": "tag", "operator": "=", "value": "promotion-blocker" }
     ]
    }
   ]
  },
  {
   "title": "TripleO bugs created in the 5 days",
   "type": "table",
   "description": "List of TripleO bugs opened in the last 5 days",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "measurement": "launchpad-bug",
     "rawSql": "SELECT id, status, tag, description, link from recent_lp",
     "slimit": "1",
     "tags": [
      { "key": "tag", "operator": "=", "value": "promotion-blocker" }
     ]
    }
   ]
  },
  { "title": "Zuul jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CI stats weekly check jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PASS",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'check' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "check" }
     ]
    },
    {
     "alias": "FAIL",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'check' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "check" }
     ]
    }
   ]
  },
  {
   "title": "CI stats weekly gate jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PASS",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'True' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'gate' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" }
     ]
    },
    {
     "alias": "FAIL",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build",
     "query": "SELECT count(\"result_num\") FROM \"build\" WHERE (\"passed\" = 'False' AND \"result\" != 'NODE_FAILURE' AND \"pipeline\" = 'gate' AND \"job_name\" =~ /tripleo-ci.*-up.*/) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "result_num" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "NODE_FAILURE" },
      { "condition": "AND", "key": "pipeline", "operator": "=", "value": "gate" }
     ]
    }
   ]
  },
  {
   "title": "Check voting  jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "alias": "PASSED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "voting", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "FAILED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "voting", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Check  jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "alias": "PASSED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "FAILED",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "build",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pipeline", "operator": "=", "value": "check" },
      { "condition": "AND", "key": "passed", "operator": "=", "value": "False" }
     ]
    }
   ]
  }
 ]
}