set -e
export RDO_VERSION='centos-master'
export DELOREAN_HOST='trunk-primary.rdoproject.org'
export DELOREAN_URL="http://$DELOREAN_HOST/centos7-master/current-tripleo/delorean.repo"
export LINKNAME='current-tripleo-rdo'
export LAST_PROMOTED_URL="http://$DELOREAN_HOST/centos7-master/$LINKNAME/delorean.repo"
export RDO_VERSION_DIR='master'
export LOCATION='testing'
export HASH_FILE='/tmp/delorean_master_current_tripleo_hash'
