# weirdo-collect-logs.sh
# A script to collect logs generated by a weirdo job
pushd $WORKSPACE/weirdo
# Don't fail script execution even if log collection fails -- the node needs to be destroyed afterwards
tox -e ansible-playbook -- -vv -i hosts playbooks/logs-ci-centos.yml -e ci_environment=ci-centos || true
popd